# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3269dd49a98176553430dfbf65053dcf2036cd8c50e18a4a8cd679577d9b2be5ff956f03e21b7d7838de73942203b3fca3a8b5c1542db44c8a7ec3fba0eea69e

test:
  secret_key_base: 5ce414dc82825b9d7ed1edbfaa7b3d034718aa462d5b142852a1bfe7115ad3574135342d9b113e4902572894e3c6db5274039d9fbd869e93c03f08c9548093ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
